import type { Metadata, Viewport } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/contexts/AuthContext";
import { PerformanceOptimizer } from "@/components/PerformanceOptimizer";
import PWAInstaller from "@/components/PWAInstaller";
import MeetingRecorder from "@/components/MeetingRecorder";
import { Toaster } from "sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Synergies4 - AI-Powered Professional Development",
  description: "AI-powered learning tailored uniquely to you and your organization. Master Agile, leadership, and mental fitness with our comprehensive training programs.",
  keywords: ["AI learning", "Agile training", "Leadership development", "Professional development", "Scrum training", "Product management", "Mental fitness"],
  authors: [{ name: "Synergies4" }],
  creator: "Synergies4",
  publisher: "Synergies4 LLC",
  
  // Favicon and icons - Generated by favicons package
  icons: {
    icon: [
      { url: "/favicon.ico", sizes: "any" },
      { url: "/favicon-16x16.png", sizes: "16x16", type: "image/png" },
      { url: "/favicon-32x32.png", sizes: "32x32", type: "image/png" },
      { url: "/favicon-48x48.png", sizes: "48x48", type: "image/png" }
    ],
    apple: [
      { url: "/apple-touch-icon.png", sizes: "180x180", type: "image/png" }
    ],
    shortcut: "/favicon.ico"
  },
  
  // Open Graph / Facebook - Removed specific image to use defaults
  openGraph: {
    type: "website",
    locale: "en_US",
    url: "https://synergies4.com",
    siteName: "Synergies4",
    title: "Synergies4 - AI-Powered Professional Development",
    description: "Transform your career with AI-powered learning. Master Agile, leadership, and mental fitness with expert-led training programs."
  },
  
  // Twitter - Removed specific image to use defaults
  twitter: {
    card: "summary",
    site: "@synergies4",
    creator: "@synergies4",
    title: "Synergies4 - AI-Powered Professional Development",
    description: "Transform your career with AI-powered learning. Master Agile, leadership, and mental fitness with expert-led training programs."
  },
  
  // Additional metadata
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  
  // Verification
  verification: {
    google: "your-google-verification-code",
    yandex: "your-yandex-verification-code",
  },
  
  // App-specific
  applicationName: "Synergies4",
  category: "Education",
  
  // PWA-specific
  manifest: "/manifest.webmanifest",
  themeColor: "#0d9488",
  appleWebApp: {
    capable: true,
    statusBarStyle: "default",
    title: "Synergies4",
  },
};

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1,
  userScalable: false, // Prevent zoom on mobile for better UX
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Favicon links - Generated by favicons package */}
        <link rel="icon" type="image/x-icon" href="/favicon.ico" />
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png" />
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png" />
        <link rel="icon" type="image/png" sizes="48x48" href="/favicon-48x48.png" />
        <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />
        <link rel="manifest" href="/manifest.webmanifest" />
        <meta name="theme-color" content="#0d9488" />
        
        {/* PWA Meta Tags */}
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="default" />
        <meta name="apple-mobile-web-app-title" content="Synergies4" />
        <meta name="mobile-web-app-capable" content="yes" />
        <meta name="msapplication-config" content="/browserconfig.xml" />
        <meta name="msapplication-TileColor" content="#0d9488" />
        <meta name="application-name" content="Synergies4" />
      </head>
      <body className={inter.className} suppressHydrationWarning>
        <PerformanceOptimizer />
        <AuthProvider>
          {children}
          <PWAInstaller />
          <MeetingRecorder />
          <Toaster />
        </AuthProvider>
      </body>
    </html>
  );
}
